name: midnightjunkies
favicon: null
layout_spectrum: 0.99188
typography_spectrum: 0.982286422746256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#282828'
    - '#db24cc'
    - '#7b7b7b'
    - '#7f1775'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
